apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.cape.sh/v1alpha1",
          "kind": "Installer",
          "metadata": {
            "name": "trycape"
          },
          "spec": {
            "acceptTOS": true,
            "chartVersion": "1.0.1",
            "installNamespace": "cape"
          }
        }
      ]
    capabilities: Basic Install
  name: cape.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Installer is the Schema for the installers API
      kind: Installer
      name: installers.operator.cape.sh
      version: v1alpha1
  description: Kubernetes data management made simple
  displayName: cape
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0ODQuNTQzMjEi
      IGhlaWdodD0iNDI0LjQwMTQ3IiB2aWV3Qm94PSIwIDAgNDg0LjU0MzIxIDQyNC40MDE0NyI+PGRl
      ZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiMyNjM0N2E7fS5jbHMtMntmaWxsOiNlZjQ2M2U7fS5jbHMt
      M3tmaWxsOm5vbmU7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5DQVBFLTRDTG9nby1WZXJ0LUNOQ0Y8
      L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMb2dvcyI+
      PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMzU5LjYxMDQ5LDE2NC4wNjcwOHEyLjYzNy0yLjIyNzQ1
      LDUuMTEzMjMtNC40NjY1OWMxLjIwODE0LTEuMDkwNzMsMi4zODA1Ny0yLjE4MjU2LDMuNTMwMjEt
      My4yNzQ5NCwyMy41MDI3OC0yMi4zMzUsMzQuNjc5MjItNDQuODg3NDEsMjcuMjM2NS02MC44Njk2
      MUMzODIuMzU5MzksNjcuMjU5LDMxNi4zMjYsNzAuMTk0NzgsMjQ4LjAwMDUsMTAyLjAxM2MtNDEu
      MzU5LDE5LjI2MDE1LTc0LjA3NjE4LDQ0LjY4ODI5LTkwLjU0NzM4LDY4LjAxNDIxLTQyLjg4NjI1
      LDEyLjc1ODktNzAuMjQ4MjYsMjguNTc4MzgtNjcuMjk5NDYsNDEuMzIuNTg2MDgsMi41MzIxNywy
      LjM0ODQ0LDQuODEwNzIsNS4xMzg3Nyw2LjgzMDU1LDMuNDk3LTkuOTExMzEsMjMuMjc1NjYtMjEu
      MjA4MzEsNTMuMDU5NzEtMzEuMzk4MjQtMi44Mjg3OSw3LjcwOTM5LTMuMzk3MjksMTQuOTAyMTkt
      MS4zNDkzMSwyMS4yMDc2Miw4LjIyNDA3LDI3LjY2MjA1LDYzLjc0NDU0LDUxLjU1ODEyLDEzMi4x
      OTY2Niw1NS4yNjIzMSw3NS4yNjEsNC4wNzI5LDEzNy42MzQyNC0xNy44MDM4OCwxMzkuMzE1LTQ4
      Ljg2MjgxQzQxOS41Nzc5MiwxOTQuNzM0OTIsMzk2LjA3MTI5LDE3Ni4xMjQ1NSwzNTkuNjEwNDks
      MTY0LjA2NzA4Wk0yNTIuNjMwOTIsMTA2Ljg4OWM0OS45NTA2OS0yMy4yNjEyOSw5OS4yODY4Ny0y
      My4xMjkwOSwxMTAuMTk1MDcuMjk1MTYsNS42MTMsMTIuMDUzMjMtLjA4MywyNy45MjMxLTEzLjcw
      NDU5LDQzLjY2MDc3LTIuMDEyNjksMi4zMjUyLTUuNDA4MzQsNS44NTc1Ny03Ljc1NzcxLDguMTY0
      MzNhNDUuNDc2NjcsNDUuNDc2NjcsMCwwLDAtNS40MTYxMi0xLjQwMjI0LDMxMS4wMDE2OSwzMTEu
      MDAxNjksMCwwLDAtNTAuNjYxNjItNi44MzJjLTguNjAxNTYtLjQ2NTQ2LTE3LjAxOTI5LS41NzIz
      OS0yNS4yMTExOC0uMzg0LTI3LjY3NDguNjM1ODctNzMuOTkxNywxMi4xMjk0LTc0Ljk1NTU3LDEy
      LjM1MzRDMTk1LjQ2ODA4LDE0My4yNzIxNSwyMjAuMTc1MTEsMTIyLjAwMzIzLDI1Mi42MzA5Miwx
      MDYuODg5Wm0tNjcuNDcwNTcsODkuNTIzNzJjLS41NTkyMS04Ljg3NDM1LDkuNzE4OTMtMTguNzI0
      NDgsMjIuNDY0OTItMjUuNDU0MjMsMTguODIzNDktOS45MzgzNiw0Ny41NzQzNC0xNS40MjczLDc5
      LjQ1MjI0LTEzLjcwMjE1LDQuNTY2NDIuMjQ3MTcsOS4wNDU3OS42NDQxNiwxMy40MzQyNCwxLjE2
      MTU4YTE4Ni43NjU1MiwxODYuNzY1NTIsMCwwLDEsMzMuNjQxOTEsNy4wMTU1MiwxOTIuOTk1Njcs
      MTkyLjk5NTY3LDAsMCwxLTQyLjAyLDI2LjI4MjY3QzI0Ni4wMzksMjEzLjE4MTQ2LDE4Ni4xODQ0
      NywyMTIuNDU1LDE4NS4xNjAzNSwxOTYuNDEyNjlabTk2Ljg2MDc4LDU0LjI4MDg4Yy0zMC44ODg2
      NS0xLjY3MTU5LTU4LjEzNDIxLTkuNzU4NzQtNzUuODQ3Ni0yMS4wOTU3LDI1LjgxMTEyLTEuOTg3
      Nyw1Ny4zNDI0My0xMC41NTY1OCw4OS4zNzgtMjUuNDc1MTFBMzAxLjkzNTQsMzAxLjkzNTQsMCww
      LDAsMzUwLjI2NjE4LDE3MS41NGMyMS40NDAyNCw5Ljc1NTE3LDM0LjY4OCwyMy40MDI2NywzMy45
      MDc0OCwzNy44MjYxNkMzODIuNzc3MzksMjM1LjE2ODA5LDMzNy4wNDIsMjUzLjY3MTA3LDI4Mi4w
      MjExMywyNTAuNjkzNTdaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNODUuMDQ2ODEsMjMzLjIw
      NjI3YTkuOTQzMyw5Ljk0MzMsMCwxLDEtMi4zOTctMTMuODU2MDlBOS45NDMxMSw5Ljk0MzExLDAs
      MCwxLDg1LjA0NjgxLDIzMy4yMDYyN1oiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzMuMDk1
      OTUsMzQ4LjQyMjEzYTMyLjk4MzIxLDMyLjk4MzIxLDAsMCwxLTEyLjkyOTY5LTEyLjI2MzY3LDM1
      Ljc1ODE2LDM1Ljc1ODE2LDAsMCwxLDAtMzUuNDYsMzIuOTk2ODcsMzIuOTk2ODcsMCwwLDEsMTIu
      OTI5NjktMTIuMjYzNjcsMzguNDE5MSwzOC40MTkxLDAsMCwxLDE4LjQ5MTIxLTQuNDIwOSwzOC44
      MDcwOCwzOC44MDcwOCwwLDAsMSwxNS42Mzg2NywzLjA0MiwzMS4zNDIxLDMxLjM0MjEsMCwwLDEs
      MTEuNzQwMjMsOC43NDYwOWwtOS44ODY3Miw5LjEyN2EyMS4yNjI2NiwyMS4yNjI2NiwwLDAsMC0x
      Ni43MzI0Mi03Ljc5NTksMjIuMjExMDgsMjIuMjExMDgsMCwwLDAtMTEuMDI3MzQsMi43MSwxOS4y
      NTg4MiwxOS4yNTg4MiwwLDAsMC03LjU1ODU5LDcuNTU3NjIsMjMuODAwNjksMjMuODAwNjksMCww
      LDAsMCwyMi4wNTU2NiwxOS4yNTksMTkuMjU5LDAsMCwwLDcuNTU4NTksNy41NTc2MiwyMi4yMTEw
      OCwyMi4yMTEwOCwwLDAsMCwxMS4wMjczNCwyLjcxLDIxLjE1MzQ5LDIxLjE1MzQ5LDAsMCwwLDE2
      LjczMjQyLTcuODkwNjNsOS44ODY3Miw5LjEyNkEzMC44MTEzNSwzMC44MTEzNSwwLDAsMSwyMDcu
      MTc4LDM0OS44MDFhMzkuMTQ4LDM5LjE0OCwwLDAsMS0xNS42ODY1MywzLjA0MkEzOC4yMTc4LDM4
      LjIxNzgsMCwwLDEsMTczLjA5NTk1LDM0OC40MjIxM1oiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9
      Ik0yNzAuMDE2ODQsMzM3LjQ0MjY0SDIzOS4xMjAzNmwtNS44OTQ1MywxNC4yNTk3NkgyMTcuNDQ0
      NThsMjkuNjYxMTMtNjYuNTQ3ODVoMTUuMjEwOTRsMjkuNzU1ODYsNjYuNTQ3ODVIMjc1LjkxMTM4
      Wm0tNC44NDg2My0xMS42OTMzNi0xMC41NTE3Ni0yNS40Nzg1Mi0xMC41NTI3MywyNS40Nzg1Mloi
      Lz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0zNDEuMzY1NDgsMjg4LjEwMTgyYTIyLjgxMzg1LDIy
      LjgxMzg1LDAsMCwxLDEwLjAyOTI5LDguMzY2MjEsMjUuMDg1ODUsMjUuMDg1ODUsMCwwLDEsMCwy
      NS42MjEwOSwyMi4zOTc2NCwyMi4zOTc2NCwwLDAsMS0xMC4wMjkyOSw4LjM2NTI0LDM3LjQ3MDc0
      LDM3LjQ3MDc0LDAsMCwxLTE1LjM1MzUyLDIuOTAwMzloLTEzLjQwNDNWMzUxLjcwMjRIMjk3LjIw
      NjNWMjg1LjE1NDU1SDMyNi4wMTJBMzYuOTgzLDM2Ljk4MywwLDAsMSwzNDEuMzY1NDgsMjg4LjEw
      MTgyWm0tNS42NTYyNSwyOS43MDlxMy42MTA4My0yLjk5NTYsMy42MTIzLTguNTA4NzksMC01LjYw
      ODg3LTMuNjEyMy04LjYwMzUxLTMuNjE1MjQtMi45OTQxNS0xMC41NTI3NC0yLjk5NTEySDMxMi42
      MDc2NnYyMy4xMDE1NmgxMi41NDg4M1EzMzIuMDk0LDMyMC44MDQ5NCwzMzUuNzA5MjMsMzE3Ljgx
      MDhaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNDE1LjU2NTY3LDMzOS4zNDRWMzUxLjcwMjRI
      MzY0LjAzODMzVjI4NS4xNTQ1NWg1MC4yOTF2MTIuMzU5MzhIMzc5LjM0NHYxNC40NTAxOWgzMC44
      OTc0NnYxMS45Nzg1MkgzNzkuMzQ0VjMzOS4zNDRaIi8+PC9nPjxnIGlkPSJHdWlkZWxpbmVzIj48
      cmVjdCBjbGFzcz0iY2xzLTMiIHdpZHRoPSI0ODQuNTQzMjEiIGhlaWdodD0iNDI0LjQwMTQ3Ii8+
      PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - namespaces
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - apps
          - extensions
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          - clusterroles
          - clusterrolebindings
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - operator.cape.sh
          resources:
          - installers
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - '*'
        - apiGroups:
          - autoscaling
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: boot
      deployments:
      - name: boot
        spec:
          replicas: 1
          selector:
            matchLabels:
              type: boot
          strategy: {}
          template:
            metadata:
              labels:
                type: boot
            spec:
              containers:
              - command:
                - cape-boot-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cape-boot-operator
                image: capesh/cape-boot-operator
                imagePullPolicy: Always
                name: boot
                resources: {}
              serviceAccountName: boot
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - disaster recovery
  - velero
  - multi-cluster deployments
  - kubefed
  - cicd
  links:
  - name: Cape
    url: https://cape.domain
  maintainers:
  - email: connect@biqmind.com
    name: Cloud native team
  maturity: alpha
  provider:
    name: biqmind
    url: https://cape.sh
  version: 1.0.0
